### ISSUE TITLE
Add whitespace to database when user puts nothing into a field when adding an account to the dashboard.

### ISSUE THREAD

**Issue by alextmacri** [hadi-naqvi/Aegis-Pass#23]
When a user is adding an account's information to the dashboard, the encryption won't work if any strings are empty. So, for any non-required fields when adding an account, replace any empty text fields with whitespace before moving on with encryptions.

**Comment by hadi-naqvi** [comment]
This bug was fixed in the following pull request: https://github.com/hadi-naqvi/Aegis-Pass/pull/29

Note that whitespaces were not used, but rather the encrypt/decrypt methods were modified to not throw exceptions when empty strings are passed through by simply returning an empty string back if the input is an empty string. This achieves the same effect that a whitespace would have.
